######################################################################
# Automatically generated by qmake (2.01a) Mon Oct 29 14:44:45 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += gerenciaInfo.h lde.h les.h mainwindow.h no.h second.h
FORMS += mainwindow.ui second.ui
SOURCES += main.cpp mainwindow.cpp second.cpp
RESOURCES += arquivorecurso.qrc
